---
deployment:
  tasks:
    - export DEPLOYPATH=/home/amaterra/app
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp .env.local $DEPLOYPATH/.env.production || true
    - source /home/amaterra/nodevenv/app/24/bin/activate
    - cd $DEPLOYPATH && npm install --production
    - cd $DEPLOYPATH && npm run build
    - touch /home/amaterra/app/tmp/restart.txt