export type Lang = "ru" | "ro" | "en";

export type HomeI18n = {
  brand: string;
  nav: string[];
  callNow: string;
  phoneNumberDisplay: string;
  phoneTel: string;
  tagline: string;
  title: string;
  description: string;
  tagline2: string;
  title2: string;
  description2: string;
  tagline3: string;
  title3: string;
  description3: string;
  book: string;
  learn: string;
  languageLabel: string;
  aboutLabel: string;
  aboutTitle: string;
  aboutDescription: string;
  aboutCta: string;
  aboutSatisfaction: string;
  aboutSatisfactionLabel: string;
  specTitle: string;
  specDescription: string;
  specServices: { title: string; description: string; image: string }[];
  findUsTitle: string;
  findUsName: string;
  findUsEmail: string;
  findUsDate: string;
  findUsTime: string;
  findUsCta: string;
  findUsLocationLabel: string;
  findUsAddress: string;
  modalTitle: string;
  modalSubtitle: string;
  modalLastName: string;
  modalFirstName: string;
  modalPhone: string;
  modalEmail: string;
  modalDate: string;
  modalSubmit: string;
  modalClose: string;
  reviewsTitle: string;
  reviewsDescription: string;
  reviewsReadMore: string;
  reviewsItems: { text: string; name: string; role: string; avatar: string }[];
  ourServicesTitle: string;
  ourServicesMain: { title: string; bullets: string[]; image: string }[];
  ourServicesMinor: string[];
  ourServicesCategories: {
    title: string;
    services: string[];
  }[];
  ourServicesFullListTitle: string;
  ourServicesSearchPlaceholder: string;
  ourServicesNoResults: string;
  ourDoctorsTitle: string;
  ourDoctorsSubtitle: string;
  ourDoctorsBottomText: string;
  workGalleryTitle: string;
  workGallerySubtitle: string;
  ourDoctors: {
    name: string;
    specialty: string;
    image: string;
  }[];
  insightsTitle: string;
  insightsItems: { date: string; title: string; text: string; image?: string }[];
  footerDescription: string;
  footerPhoneLabel: string;
  footerEmailLabel: string;
  footerEmail: string;
  footerHoursLabel: string;
  footerHours: string[];
  footerCopyright: string;
  footerLinksCol1: string[];
  footerLinksCol2: string[];
  footerSocial: string[];
  footerSocialLinks: string[];
};
