export type Lang = "ru" | "ro" | "en";

export type HomeI18n = {
  brand: string;
  nav: string[];
  callNow: string;
  phoneNumberDisplay: string;
  phoneTel: string;
  tagline: string;
  title: string;
  description: string;
  book: string;
  learn: string;
  languageLabel: string;
  aboutLabel: string;
  aboutTitle: string;
  aboutDescription: string;
  aboutCta: string;
  aboutSatisfaction: string;
  aboutSatisfactionLabel: string;
  specTitle: string;
  specDescription: string;
  specServices: { title: string; description: string; image: string }[];
  findUsTitle: string;
  findUsName: string;
  findUsEmail: string;
  findUsDate: string;
  findUsTime: string;
  findUsCta: string;
  findUsLocationLabel: string;
  findUsAddress: string;
  modalTitle: string;
  modalSubtitle: string;
  modalLastName: string;
  modalFirstName: string;
  modalPhone: string;
  modalEmail: string;
  modalDate: string;
  modalSubmit: string;
  modalClose: string;
  reviewsTitle: string;
  reviewsDescription: string;
  reviewsReadMore: string;
  reviewsItems: { text: string; name: string; role: string; avatar: string }[];
  ourServicesTitle: string;
  ourServicesMain: { title: string; bullets: string[]; image: string }[];
  ourServicesMinor: string[];
  insightsTitle: string;
  insightsItems: { date: string; title: string; text: string; image?: string }[];
  footerDescription: string;
  footerPhoneLabel: string;
  footerEmailLabel: string;
  footerEmail: string;
  footerHoursLabel: string;
  footerHours: string[];
  footerCopyright: string;
  footerLinksCol1: string[];
  footerLinksCol2: string[];
  footerSocial: string[];
};
